//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Exchange.WebServices.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Exchange.WebServices.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountIsLocked.
        /// </summary>
        internal static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalPropertyIsNull.
        /// </summary>
        internal static string AdditionalPropertyIsNull {
            get {
                return ResourceManager.GetString("AdditionalPropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentIsBlankString.
        /// </summary>
        internal static string ArgumentIsBlankString {
            get {
                return ResourceManager.GetString("ArgumentIsBlankString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrayMustHaveAtLeastOneElement.
        /// </summary>
        internal static string ArrayMustHaveAtLeastOneElement {
            get {
                return ResourceManager.GetString("ArrayMustHaveAtLeastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrayMustHaveSingleDimension.
        /// </summary>
        internal static string ArrayMustHaveSingleDimension {
            get {
                return ResourceManager.GetString("ArrayMustHaveSingleDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtLeastOneAttachmentCouldNotBeDeleted.
        /// </summary>
        internal static string AtLeastOneAttachmentCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("AtLeastOneAttachmentCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentCannotBeUpdated.
        /// </summary>
        internal static string AttachmentCannotBeUpdated {
            get {
                return ResourceManager.GetString("AttachmentCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentCollectionNotLoaded.
        /// </summary>
        internal static string AttachmentCollectionNotLoaded {
            get {
                return ResourceManager.GetString("AttachmentCollectionNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentCreationFailed.
        /// </summary>
        internal static string AttachmentCreationFailed {
            get {
                return ResourceManager.GetString("AttachmentCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentItemTypeMismatch.
        /// </summary>
        internal static string AttachmentItemTypeMismatch {
            get {
                return ResourceManager.GetString("AttachmentItemTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeValueCannotBeSerialized.
        /// </summary>
        internal static string AttributeValueCannotBeSerialized {
            get {
                return ResourceManager.GetString("AttributeValueCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverCouldNotBeLocated.
        /// </summary>
        internal static string AutodiscoverCouldNotBeLocated {
            get {
                return ResourceManager.GetString("AutodiscoverCouldNotBeLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverDidNotReturnEwsUrl.
        /// </summary>
        internal static string AutodiscoverDidNotReturnEwsUrl {
            get {
                return ResourceManager.GetString("AutodiscoverDidNotReturnEwsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverError.
        /// </summary>
        internal static string AutodiscoverError {
            get {
                return ResourceManager.GetString("AutodiscoverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverInvalidSettingForOutlookProvider.
        /// </summary>
        internal static string AutodiscoverInvalidSettingForOutlookProvider {
            get {
                return ResourceManager.GetString("AutodiscoverInvalidSettingForOutlookProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverRedirectBlocked.
        /// </summary>
        internal static string AutodiscoverRedirectBlocked {
            get {
                return ResourceManager.GetString("AutodiscoverRedirectBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverServiceIncompatibleWithRequestVersion.
        /// </summary>
        internal static string AutodiscoverServiceIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("AutodiscoverServiceIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutodiscoverServiceRequestRequiresDomainOrUrl.
        /// </summary>
        internal static string AutodiscoverServiceRequestRequiresDomainOrUrl {
            get {
                return ResourceManager.GetString("AutodiscoverServiceRequestRequiresDomainOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BothSearchFilterAndQueryStringCannotBeSpecified.
        /// </summary>
        internal static string BothSearchFilterAndQueryStringCannotBeSpecified {
            get {
                return ResourceManager.GetString("BothSearchFilterAndQueryStringCannotBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddRequestHeader.
        /// </summary>
        internal static string CannotAddRequestHeader {
            get {
                return ResourceManager.GetString("CannotAddRequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotAddSubscriptionToLiveConnection.
        /// </summary>
        internal static string CannotAddSubscriptionToLiveConnection {
            get {
                return ResourceManager.GetString("CannotAddSubscriptionToLiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotCallConnectDuringLiveConnection.
        /// </summary>
        internal static string CannotCallConnectDuringLiveConnection {
            get {
                return ResourceManager.GetString("CannotCallConnectDuringLiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotCallDisconnectWithNoLiveConnection.
        /// </summary>
        internal static string CannotCallDisconnectWithNoLiveConnection {
            get {
                return ResourceManager.GetString("CannotCallDisconnectWithNoLiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotConvertBetweenTimeZones.
        /// </summary>
        internal static string CannotConvertBetweenTimeZones {
            get {
                return ResourceManager.GetString("CannotConvertBetweenTimeZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotRemoveSubscriptionFromLiveConnection.
        /// </summary>
        internal static string CannotRemoveSubscriptionFromLiveConnection {
            get {
                return ResourceManager.GetString("CannotRemoveSubscriptionFromLiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotSaveNotNewUserConfiguration.
        /// </summary>
        internal static string CannotSaveNotNewUserConfiguration {
            get {
                return ResourceManager.GetString("CannotSaveNotNewUserConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotSetBothImpersonatedAndPrivilegedUser.
        /// </summary>
        internal static string CannotSetBothImpersonatedAndPrivilegedUser {
            get {
                return ResourceManager.GetString("CannotSetBothImpersonatedAndPrivilegedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotSetDelegateFolderPermissionLevelToCustom.
        /// </summary>
        internal static string CannotSetDelegateFolderPermissionLevelToCustom {
            get {
                return ResourceManager.GetString("CannotSetDelegateFolderPermissionLevelToCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotSetPermissionLevelToCustom.
        /// </summary>
        internal static string CannotSetPermissionLevelToCustom {
            get {
                return ResourceManager.GetString("CannotSetPermissionLevelToCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotSubscribeToStatusEvents.
        /// </summary>
        internal static string CannotSubscribeToStatusEvents {
            get {
                return ResourceManager.GetString("CannotSubscribeToStatusEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotUpdateNewUserConfiguration.
        /// </summary>
        internal static string CannotUpdateNewUserConfiguration {
            get {
                return ResourceManager.GetString("CannotUpdateNewUserConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificateHasNoPrivateKey.
        /// </summary>
        internal static string CertificateHasNoPrivateKey {
            get {
                return ResourceManager.GetString("CertificateHasNoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassIncompatibleWithRequestVersion.
        /// </summary>
        internal static string ClassIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("ClassIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectionIsEmpty.
        /// </summary>
        internal static string CollectionIsEmpty {
            get {
                return ResourceManager.GetString("CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactGroupMemberCannotBeUpdatedWithoutBeingLoadedFirst.
        /// </summary>
        internal static string ContactGroupMemberCannotBeUpdatedWithoutBeingLoadedFirst {
            get {
                return ResourceManager.GetString("ContactGroupMemberCannotBeUpdatedWithoutBeingLoadedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateItemsDoesNotAllowAttachments.
        /// </summary>
        internal static string CreateItemsDoesNotAllowAttachments {
            get {
                return ResourceManager.GetString("CreateItemsDoesNotAllowAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateItemsDoesNotHandleExistingItems.
        /// </summary>
        internal static string CreateItemsDoesNotHandleExistingItems {
            get {
                return ResourceManager.GetString("CreateItemsDoesNotHandleExistingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CredentialsRequired.
        /// </summary>
        internal static string CredentialsRequired {
            get {
                return ResourceManager.GetString("CredentialsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPositionNotElementStart.
        /// </summary>
        internal static string CurrentPositionNotElementStart {
            get {
                return ResourceManager.GetString("CurrentPositionNotElementStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfMonthMustBeBetween1And31.
        /// </summary>
        internal static string DayOfMonthMustBeBetween1And31 {
            get {
                return ResourceManager.GetString("DayOfMonthMustBeBetween1And31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfMonthMustBeSpecifiedForRecurrencePattern.
        /// </summary>
        internal static string DayOfMonthMustBeSpecifiedForRecurrencePattern {
            get {
                return ResourceManager.GetString("DayOfMonthMustBeSpecifiedForRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfTheWeekMustBeSpecifiedForRecurrencePattern.
        /// </summary>
        internal static string DayOfTheWeekMustBeSpecifiedForRecurrencePattern {
            get {
                return ResourceManager.GetString("DayOfTheWeekMustBeSpecifiedForRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfWeekIndexMustBeSpecifiedForRecurrencePattern.
        /// </summary>
        internal static string DayOfWeekIndexMustBeSpecifiedForRecurrencePattern {
            get {
                return ResourceManager.GetString("DayOfWeekIndexMustBeSpecifiedForRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaysOfTheWeekNotSpecified.
        /// </summary>
        internal static string DaysOfTheWeekNotSpecified {
            get {
                return ResourceManager.GetString("DaysOfTheWeekNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelegateUserHasInvalidUserId.
        /// </summary>
        internal static string DelegateUserHasInvalidUserId {
            get {
                return ResourceManager.GetString("DelegateUserHasInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteInvalidForUnsavedUserConfiguration.
        /// </summary>
        internal static string DeleteInvalidForUnsavedUserConfiguration {
            get {
                return ResourceManager.GetString("DeleteInvalidForUnsavedUserConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletingThisObjectTypeNotAuthorized.
        /// </summary>
        internal static string DeletingThisObjectTypeNotAuthorized {
            get {
                return ResourceManager.GetString("DeletingThisObjectTypeNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DurationMustBeSpecifiedWhenScheduled.
        /// </summary>
        internal static string DurationMustBeSpecifiedWhenScheduled {
            get {
                return ResourceManager.GetString("DurationMustBeSpecifiedWhenScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementNotFound.
        /// </summary>
        internal static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementValueCannotBeSerialized.
        /// </summary>
        internal static string ElementValueCannotBeSerialized {
            get {
                return ResourceManager.GetString("ElementValueCannotBeSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDateMustBeGreaterThanStartDate.
        /// </summary>
        internal static string EndDateMustBeGreaterThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreaterThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumValueIncompatibleWithRequestVersion.
        /// </summary>
        internal static string EnumValueIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("EnumValueIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EqualityComparisonFilterIsInvalid.
        /// </summary>
        internal static string EqualityComparisonFilterIsInvalid {
            get {
                return ResourceManager.GetString("EqualityComparisonFilterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedStartElement.
        /// </summary>
        internal static string ExpectedStartElement {
            get {
                return ResourceManager.GetString("ExpectedStartElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileAttachmentContentIsNotSet.
        /// </summary>
        internal static string FileAttachmentContentIsNotSet {
            get {
                return ResourceManager.GetString("FileAttachmentContentIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderPermissionHasInvalidUserId.
        /// </summary>
        internal static string FolderPermissionHasInvalidUserId {
            get {
                return ResourceManager.GetString("FolderPermissionHasInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderPermissionLevelMustBeSet.
        /// </summary>
        internal static string FolderPermissionLevelMustBeSet {
            get {
                return ResourceManager.GetString("FolderPermissionLevelMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderToUpdateCannotBeNullOrNew.
        /// </summary>
        internal static string FolderToUpdateCannotBeNullOrNew {
            get {
                return ResourceManager.GetString("FolderToUpdateCannotBeNullOrNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FolderTypeNotCompatible.
        /// </summary>
        internal static string FolderTypeNotCompatible {
            get {
                return ResourceManager.GetString("FolderTypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrequencyMustBeBetween1And1440.
        /// </summary>
        internal static string FrequencyMustBeBetween1And1440 {
            get {
                return ResourceManager.GetString("FrequencyMustBeBetween1And1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoldIdParameterIsNotSpecified.
        /// </summary>
        internal static string HoldIdParameterIsNotSpecified {
            get {
                return ResourceManager.GetString("HoldIdParameterIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoldMailboxesParameterIsNotSpecified.
        /// </summary>
        internal static string HoldMailboxesParameterIsNotSpecified {
            get {
                return ResourceManager.GetString("HoldMailboxesParameterIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HourMustBeBetween0And23.
        /// </summary>
        internal static string HourMustBeBetween0And23 {
            get {
                return ResourceManager.GetString("HourMustBeBetween0And23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpsIsRequired.
        /// </summary>
        internal static string HttpsIsRequired {
            get {
                return ResourceManager.GetString("HttpsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdAlreadyInList.
        /// </summary>
        internal static string IdAlreadyInList {
            get {
                return ResourceManager.GetString("IdAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdPropertyMustBeSet.
        /// </summary>
        internal static string IdPropertyMustBeSet {
            get {
                return ResourceManager.GetString("IdPropertyMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IEnumerableDoesNotContainThatManyObject.
        /// </summary>
        internal static string IEnumerableDoesNotContainThatManyObject {
            get {
                return ResourceManager.GetString("IEnumerableDoesNotContainThatManyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncompatibleTypeForArray.
        /// </summary>
        internal static string IncompatibleTypeForArray {
            get {
                return ResourceManager.GetString("IncompatibleTypeForArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexIsOutOfRange.
        /// </summary>
        internal static string IndexIsOutOfRange {
            get {
                return ResourceManager.GetString("IndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntervalMustBeGreaterOrEqualToOne.
        /// </summary>
        internal static string IntervalMustBeGreaterOrEqualToOne {
            get {
                return ResourceManager.GetString("IntervalMustBeGreaterOrEqualToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAsyncResult.
        /// </summary>
        internal static string InvalidAsyncResult {
            get {
                return ResourceManager.GetString("InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAttributeValue.
        /// </summary>
        internal static string InvalidAttributeValue {
            get {
                return ResourceManager.GetString("InvalidAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAuthScheme.
        /// </summary>
        internal static string InvalidAuthScheme {
            get {
                return ResourceManager.GetString("InvalidAuthScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverDomain.
        /// </summary>
        internal static string InvalidAutodiscoverDomain {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverDomainsCount.
        /// </summary>
        internal static string InvalidAutodiscoverDomainsCount {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverDomainsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverRequest.
        /// </summary>
        internal static string InvalidAutodiscoverRequest {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverServiceResponse.
        /// </summary>
        internal static string InvalidAutodiscoverServiceResponse {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverServiceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverSettingsCount.
        /// </summary>
        internal static string InvalidAutodiscoverSettingsCount {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverSettingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverSmtpAddress.
        /// </summary>
        internal static string InvalidAutodiscoverSmtpAddress {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverSmtpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAutodiscoverSmtpAddressesCount.
        /// </summary>
        internal static string InvalidAutodiscoverSmtpAddressesCount {
            get {
                return ResourceManager.GetString("InvalidAutodiscoverSmtpAddressesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDateTime.
        /// </summary>
        internal static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDomainName.
        /// </summary>
        internal static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidElementStringValue.
        /// </summary>
        internal static string InvalidElementStringValue {
            get {
                return ResourceManager.GetString("InvalidElementStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidEmailAddress.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidFrequencyValue.
        /// </summary>
        internal static string InvalidFrequencyValue {
            get {
                return ResourceManager.GetString("InvalidFrequencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidMailboxType.
        /// </summary>
        internal static string InvalidMailboxType {
            get {
                return ResourceManager.GetString("InvalidMailboxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOAuthToken.
        /// </summary>
        internal static string InvalidOAuthToken {
            get {
                return ResourceManager.GetString("InvalidOAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOrderBy.
        /// </summary>
        internal static string InvalidOrderBy {
            get {
                return ResourceManager.GetString("InvalidOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOrUnsupportedTimeZoneDefinition.
        /// </summary>
        internal static string InvalidOrUnsupportedTimeZoneDefinition {
            get {
                return ResourceManager.GetString("InvalidOrUnsupportedTimeZoneDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPropertyValueNotInRange.
        /// </summary>
        internal static string InvalidPropertyValueNotInRange {
            get {
                return ResourceManager.GetString("InvalidPropertyValueNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidRecurrencePattern.
        /// </summary>
        internal static string InvalidRecurrencePattern {
            get {
                return ResourceManager.GetString("InvalidRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidRecurrenceRange.
        /// </summary>
        internal static string InvalidRecurrenceRange {
            get {
                return ResourceManager.GetString("InvalidRecurrenceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidRedirectionResponseReturned.
        /// </summary>
        internal static string InvalidRedirectionResponseReturned {
            get {
                return ResourceManager.GetString("InvalidRedirectionResponseReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidSortByPropertyForMailboxSearch.
        /// </summary>
        internal static string InvalidSortByPropertyForMailboxSearch {
            get {
                return ResourceManager.GetString("InvalidSortByPropertyForMailboxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidTimeoutValue.
        /// </summary>
        internal static string InvalidTimeoutValue {
            get {
                return ResourceManager.GetString("InvalidTimeoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUser.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemAttachmentCannotBeUpdated.
        /// </summary>
        internal static string ItemAttachmentCannotBeUpdated {
            get {
                return ResourceManager.GetString("ItemAttachmentCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemAttachmentMustBeNamed.
        /// </summary>
        internal static string ItemAttachmentMustBeNamed {
            get {
                return ResourceManager.GetString("ItemAttachmentMustBeNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemIsOutOfDate.
        /// </summary>
        internal static string ItemIsOutOfDate {
            get {
                return ResourceManager.GetString("ItemIsOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemToUpdateCannotBeNullOrNew.
        /// </summary>
        internal static string ItemToUpdateCannotBeNullOrNew {
            get {
                return ResourceManager.GetString("ItemToUpdateCannotBeNullOrNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTypeNotCompatible.
        /// </summary>
        internal static string ItemTypeNotCompatible {
            get {
                return ResourceManager.GetString("ItemTypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonDeserializationNotImplemented.
        /// </summary>
        internal static string JsonDeserializationNotImplemented {
            get {
                return ResourceManager.GetString("JsonDeserializationNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonSerializationNotImplemented.
        /// </summary>
        internal static string JsonSerializationNotImplemented {
            get {
                return ResourceManager.GetString("JsonSerializationNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingThisObjectTypeNotSupported.
        /// </summary>
        internal static string LoadingThisObjectTypeNotSupported {
            get {
                return ResourceManager.GetString("LoadingThisObjectTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailboxesParameterIsNotSpecified.
        /// </summary>
        internal static string MailboxesParameterIsNotSpecified {
            get {
                return ResourceManager.GetString("MailboxesParameterIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailboxQueriesParameterIsNotSpecified.
        /// </summary>
        internal static string MailboxQueriesParameterIsNotSpecified {
            get {
                return ResourceManager.GetString("MailboxQueriesParameterIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxChangesMustBeBetween1And512.
        /// </summary>
        internal static string MaxChangesMustBeBetween1And512 {
            get {
                return ResourceManager.GetString("MaxChangesMustBeBetween1And512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaximumRedirectionHopsExceeded.
        /// </summary>
        internal static string MaximumRedirectionHopsExceeded {
            get {
                return ResourceManager.GetString("MaximumRedirectionHopsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxScpHopsExceeded.
        /// </summary>
        internal static string MaxScpHopsExceeded {
            get {
                return ResourceManager.GetString("MaxScpHopsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MergedFreeBusyIntervalMustBeSmallerThanTimeWindow.
        /// </summary>
        internal static string MergedFreeBusyIntervalMustBeSmallerThanTimeWindow {
            get {
                return ResourceManager.GetString("MergedFreeBusyIntervalMustBeSmallerThanTimeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodIncompatibleWithRequestVersion.
        /// </summary>
        internal static string MethodIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("MethodIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinuteMustBeBetween0And59.
        /// </summary>
        internal static string MinuteMustBeBetween0And59 {
            get {
                return ResourceManager.GetString("MinuteMustBeBetween0And59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinutesMustBeBetween0And1439.
        /// </summary>
        internal static string MinutesMustBeBetween0And1439 {
            get {
                return ResourceManager.GetString("MinutesMustBeBetween0And1439", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthMustBeSpecifiedForRecurrencePattern.
        /// </summary>
        internal static string MonthMustBeSpecifiedForRecurrencePattern {
            get {
                return ResourceManager.GetString("MonthMustBeSpecifiedForRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultipleContactPhotosInAttachment.
        /// </summary>
        internal static string MultipleContactPhotosInAttachment {
            get {
                return ResourceManager.GetString("MultipleContactPhotosInAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MustLoadOrAssignPropertyBeforeAccess.
        /// </summary>
        internal static string MustLoadOrAssignPropertyBeforeAccess {
            get {
                return ResourceManager.GetString("MustLoadOrAssignPropertyBeforeAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewMessagesWithAttachmentsCannotBeSentDirectly.
        /// </summary>
        internal static string NewMessagesWithAttachmentsCannotBeSentDirectly {
            get {
                return ResourceManager.GetString("NewMessagesWithAttachmentsCannotBeSentDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoAppropriateConstructorForItemClass.
        /// </summary>
        internal static string NoAppropriateConstructorForItemClass {
            get {
                return ResourceManager.GetString("NoAppropriateConstructorForItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoError.
        /// </summary>
        internal static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonSummaryPropertyCannotBeUsed.
        /// </summary>
        internal static string NonSummaryPropertyCannotBeUsed {
            get {
                return ResourceManager.GetString("NonSummaryPropertyCannotBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSoapOrWsSecurityEndpointAvailable.
        /// </summary>
        internal static string NoSoapOrWsSecurityEndpointAvailable {
            get {
                return ResourceManager.GetString("NoSoapOrWsSecurityEndpointAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSubscriptionsOnConnection.
        /// </summary>
        internal static string NoSubscriptionsOnConnection {
            get {
                return ResourceManager.GetString("NoSubscriptionsOnConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullStringArrayElementInvalid.
        /// </summary>
        internal static string NullStringArrayElementInvalid {
            get {
                return ResourceManager.GetString("NullStringArrayElementInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfDaysMustBePositive.
        /// </summary>
        internal static string NumberOfDaysMustBePositive {
            get {
                return ResourceManager.GetString("NumberOfDaysMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfOccurrencesMustBeGreaterThanZero.
        /// </summary>
        internal static string NumberOfOccurrencesMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("NumberOfOccurrencesMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectDoesNotHaveId.
        /// </summary>
        internal static string ObjectDoesNotHaveId {
            get {
                return ResourceManager.GetString("ObjectDoesNotHaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectTypeIncompatibleWithRequestVersion.
        /// </summary>
        internal static string ObjectTypeIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("ObjectTypeIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectTypeNotSupported.
        /// </summary>
        internal static string ObjectTypeNotSupported {
            get {
                return ResourceManager.GetString("ObjectTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OccurrenceIndexMustBeGreaterThanZero.
        /// </summary>
        internal static string OccurrenceIndexMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("OccurrenceIndexMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetMustBeGreaterThanZero.
        /// </summary>
        internal static string OffsetMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("OffsetMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationDoesNotSupportAttachments.
        /// </summary>
        internal static string OperationDoesNotSupportAttachments {
            get {
                return ResourceManager.GetString("OperationDoesNotSupportAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationNotSupportedForPropertyDefinitionType.
        /// </summary>
        internal static string OperationNotSupportedForPropertyDefinitionType {
            get {
                return ResourceManager.GetString("OperationNotSupportedForPropertyDefinitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterIncompatibleWithRequestVersion.
        /// </summary>
        internal static string ParameterIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("ParameterIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentFolderDoesNotHaveId.
        /// </summary>
        internal static string ParentFolderDoesNotHaveId {
            get {
                return ResourceManager.GetString("ParentFolderDoesNotHaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerTokenIncompatibleWithRequestVersion.
        /// </summary>
        internal static string PartnerTokenIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("PartnerTokenIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerTokenRequestRequiresUrl.
        /// </summary>
        internal static string PartnerTokenRequestRequiresUrl {
            get {
                return ResourceManager.GetString("PartnerTokenRequestRequiresUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercentCompleteMustBeBetween0And100.
        /// </summary>
        internal static string PercentCompleteMustBeBetween0And100 {
            get {
                return ResourceManager.GetString("PercentCompleteMustBeBetween0And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodNotFound.
        /// </summary>
        internal static string PeriodNotFound {
            get {
                return ResourceManager.GetString("PeriodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionLevelInvalidForNonCalendarFolder.
        /// </summary>
        internal static string PermissionLevelInvalidForNonCalendarFolder {
            get {
                return ResourceManager.GetString("PermissionLevelInvalidForNonCalendarFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneCallAlreadyDisconnected.
        /// </summary>
        internal static string PhoneCallAlreadyDisconnected {
            get {
                return ResourceManager.GetString("PhoneCallAlreadyDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyAlreadyExistsInOrderByCollection.
        /// </summary>
        internal static string PropertyAlreadyExistsInOrderByCollection {
            get {
                return ResourceManager.GetString("PropertyAlreadyExistsInOrderByCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyCannotBeDeleted.
        /// </summary>
        internal static string PropertyCannotBeDeleted {
            get {
                return ResourceManager.GetString("PropertyCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyCannotBeUpdated.
        /// </summary>
        internal static string PropertyCannotBeUpdated {
            get {
                return ResourceManager.GetString("PropertyCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyCollectionSizeMismatch.
        /// </summary>
        internal static string PropertyCollectionSizeMismatch {
            get {
                return ResourceManager.GetString("PropertyCollectionSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyDefinitionPropertyMustBeSet.
        /// </summary>
        internal static string PropertyDefinitionPropertyMustBeSet {
            get {
                return ResourceManager.GetString("PropertyDefinitionPropertyMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyDefinitionTypeMismatch.
        /// </summary>
        internal static string PropertyDefinitionTypeMismatch {
            get {
                return ResourceManager.GetString("PropertyDefinitionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyIncompatibleWithRequestVersion.
        /// </summary>
        internal static string PropertyIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("PropertyIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyIsReadOnly.
        /// </summary>
        internal static string PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertySetCannotBeModified.
        /// </summary>
        internal static string PropertySetCannotBeModified {
            get {
                return ResourceManager.GetString("PropertySetCannotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyTypeIncompatibleWhenUpdatingCollection.
        /// </summary>
        internal static string PropertyTypeIncompatibleWhenUpdatingCollection {
            get {
                return ResourceManager.GetString("PropertyTypeIncompatibleWhenUpdatingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyValueMustBeSpecifiedForRecurrencePattern.
        /// </summary>
        internal static string PropertyValueMustBeSpecifiedForRecurrencePattern {
            get {
                return ResourceManager.GetString("PropertyValueMustBeSpecifiedForRecurrencePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadAccessInvalidForNonCalendarFolder.
        /// </summary>
        internal static string ReadAccessInvalidForNonCalendarFolder {
            get {
                return ResourceManager.GetString("ReadAccessInvalidForNonCalendarFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecurrencePatternMustHaveStartDate.
        /// </summary>
        internal static string RecurrencePatternMustHaveStartDate {
            get {
                return ResourceManager.GetString("RecurrencePatternMustHaveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegenerationPatternsOnlyValidForTasks.
        /// </summary>
        internal static string RegenerationPatternsOnlyValidForTasks {
            get {
                return ResourceManager.GetString("RegenerationPatternsOnlyValidForTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestIncompatibleWithRequestVersion.
        /// </summary>
        internal static string RequestIncompatibleWithRequestVersion {
            get {
                return ResourceManager.GetString("RequestIncompatibleWithRequestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchFilterAtIndexIsInvalid.
        /// </summary>
        internal static string SearchFilterAtIndexIsInvalid {
            get {
                return ResourceManager.GetString("SearchFilterAtIndexIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchFilterComparisonValueTypeIsNotSupported.
        /// </summary>
        internal static string SearchFilterComparisonValueTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SearchFilterComparisonValueTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchFilterMustBeSet.
        /// </summary>
        internal static string SearchFilterMustBeSet {
            get {
                return ResourceManager.GetString("SearchFilterMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchParametersRootFolderIdsEmpty.
        /// </summary>
        internal static string SearchParametersRootFolderIdsEmpty {
            get {
                return ResourceManager.GetString("SearchParametersRootFolderIdsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondMustBeBetween0And59.
        /// </summary>
        internal static string SecondMustBeBetween0And59 {
            get {
                return ResourceManager.GetString("SecondMustBeBetween0And59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerErrorAndStackTraceDetails.
        /// </summary>
        internal static string ServerErrorAndStackTraceDetails {
            get {
                return ResourceManager.GetString("ServerErrorAndStackTraceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerVersionNotSupported.
        /// </summary>
        internal static string ServerVersionNotSupported {
            get {
                return ResourceManager.GetString("ServerVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceObjectAlreadyHasId.
        /// </summary>
        internal static string ServiceObjectAlreadyHasId {
            get {
                return ResourceManager.GetString("ServiceObjectAlreadyHasId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceObjectDoesNotHaveId.
        /// </summary>
        internal static string ServiceObjectDoesNotHaveId {
            get {
                return ResourceManager.GetString("ServiceObjectDoesNotHaveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRequestFailed.
        /// </summary>
        internal static string ServiceRequestFailed {
            get {
                return ResourceManager.GetString("ServiceRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceResponseDoesNotContainXml.
        /// </summary>
        internal static string ServiceResponseDoesNotContainXml {
            get {
                return ResourceManager.GetString("ServiceResponseDoesNotContainXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceUrlMustBeSet.
        /// </summary>
        internal static string ServiceUrlMustBeSet {
            get {
                return ResourceManager.GetString("ServiceUrlMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTimeZoneRequired.
        /// </summary>
        internal static string StartTimeZoneRequired {
            get {
                return ResourceManager.GetString("StartTimeZoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagValueIsOutOfRange.
        /// </summary>
        internal static string TagValueIsOutOfRange {
            get {
                return ResourceManager.GetString("TagValueIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeoutMustBeBetween1And1440.
        /// </summary>
        internal static string TimeoutMustBeBetween1And1440 {
            get {
                return ResourceManager.GetString("TimeoutMustBeBetween1And1440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeoutMustBeGreaterThanZero.
        /// </summary>
        internal static string TimeoutMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TimeoutMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeWindowStartTimeMustBeGreaterThanEndTime.
        /// </summary>
        internal static string TimeWindowStartTimeMustBeGreaterThanEndTime {
            get {
                return ResourceManager.GetString("TimeWindowStartTimeMustBeGreaterThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TooFewServiceReponsesReturned.
        /// </summary>
        internal static string TooFewServiceReponsesReturned {
            get {
                return ResourceManager.GetString("TooFewServiceReponsesReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransitionGroupNotFound.
        /// </summary>
        internal static string TransitionGroupNotFound {
            get {
                return ResourceManager.GetString("TransitionGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedElement.
        /// </summary>
        internal static string UnexpectedElement {
            get {
                return ResourceManager.GetString("UnexpectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedElementType.
        /// </summary>
        internal static string UnexpectedElementType {
            get {
                return ResourceManager.GetString("UnexpectedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedEndOfXmlDocument.
        /// </summary>
        internal static string UnexpectedEndOfXmlDocument {
            get {
                return ResourceManager.GetString("UnexpectedEndOfXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnknownTimeZonePeriodTransitionType.
        /// </summary>
        internal static string UnknownTimeZonePeriodTransitionType {
            get {
                return ResourceManager.GetString("UnknownTimeZonePeriodTransitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsupportedTimeZonePeriodTransitionTarget.
        /// </summary>
        internal static string UnsupportedTimeZonePeriodTransitionTarget {
            get {
                return ResourceManager.GetString("UnsupportedTimeZonePeriodTransitionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsupportedWebProtocol.
        /// </summary>
        internal static string UnsupportedWebProtocol {
            get {
                return ResourceManager.GetString("UnsupportedWebProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateItemsDoesNotAllowAttachments.
        /// </summary>
        internal static string UpdateItemsDoesNotAllowAttachments {
            get {
                return ResourceManager.GetString("UpdateItemsDoesNotAllowAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateItemsDoesNotSupportNewOrUnchangedItems.
        /// </summary>
        internal static string UpdateItemsDoesNotSupportNewOrUnchangedItems {
            get {
                return ResourceManager.GetString("UpdateItemsDoesNotSupportNewOrUnchangedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIdForDelegateUserNotSpecified.
        /// </summary>
        internal static string UserIdForDelegateUserNotSpecified {
            get {
                return ResourceManager.GetString("UserIdForDelegateUserNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationFailed.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueCannotBeConverted.
        /// </summary>
        internal static string ValueCannotBeConverted {
            get {
                return ResourceManager.GetString("ValueCannotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueMustBeGreaterThanZero.
        /// </summary>
        internal static string ValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueOfTypeCannotBeConverted.
        /// </summary>
        internal static string ValueOfTypeCannotBeConverted {
            get {
                return ResourceManager.GetString("ValueOfTypeCannotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuePropertyMustBeSet.
        /// </summary>
        internal static string ValuePropertyMustBeSet {
            get {
                return ResourceManager.GetString("ValuePropertyMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuePropertyNotAssigned.
        /// </summary>
        internal static string ValuePropertyNotAssigned {
            get {
                return ResourceManager.GetString("ValuePropertyNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValuePropertyNotLoaded.
        /// </summary>
        internal static string ValuePropertyNotLoaded {
            get {
                return ResourceManager.GetString("ValuePropertyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WLIDCredentialsCannotBeUsedWithLegacyAutodiscover.
        /// </summary>
        internal static string WLIDCredentialsCannotBeUsedWithLegacyAutodiscover {
            get {
                return ResourceManager.GetString("WLIDCredentialsCannotBeUsedWithLegacyAutodiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XsDurationCouldNotBeParsed.
        /// </summary>
        internal static string XsDurationCouldNotBeParsed {
            get {
                return ResourceManager.GetString("XsDurationCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZeroLengthArrayInvalid.
        /// </summary>
        internal static string ZeroLengthArrayInvalid {
            get {
                return ResourceManager.GetString("ZeroLengthArrayInvalid", resourceCulture);
            }
        }
    }
}
